[project]
name = "earthmacs"
version = "0.0.1"
authors = ["clmn"]

[dependencies]
ncurses = "5.85.0"
termkey-rs = { git = "git://github.com/mathall/termkey-rs.git" }
syntect = "1.0.4"
libc = "0.2.20"
lazy_static = "0.1.*"
regex = "0.1"
fuzzyrusty = "0.1.0"
